# typed: false
# frozen_string_literal: true

# voluntold — the agent runtime CLI.
#
# AUTO-GENERATED by the voluntold release CI (cli_release →
# cli/scripts/render-formula.sh) and force-pushed on every release. Do not edit
# by hand; changes will be overwritten. The binaries are obfuscated with garble
# and published to https://dl.voluntold.ai.
class Voluntold < Formula
  desc "Agent runtime that routes issue-board work to AI coding agents"
  homepage "https://voluntold.ai"
  version "0.12.50"

  on_macos do
    on_arm do
      url "https://dl.voluntold.ai/v0.12.50/voluntold-darwin-arm64"
      sha256 "66bd529675dfad2c976a01d21825567ff10f8d727a4425ab94134a9edf0edd15"
    end
    on_intel do
      url "https://dl.voluntold.ai/v0.12.50/voluntold-darwin-amd64"
      sha256 "70a12c09382b1e209183fcea03cfb8bd803637b2bf9e4bd93a9724e572127b90"
    end
  end

  on_linux do
    on_arm do
      url "https://dl.voluntold.ai/v0.12.50/voluntold-linux-arm64"
      sha256 "1b7c5077cfd6273ccd01a10dfacad2b205795563da4641015cefa1c3a42009f1"
    end
    on_intel do
      url "https://dl.voluntold.ai/v0.12.50/voluntold-linux-amd64"
      sha256 "54a4add24a0a01fa85307646cd837edf92ae33ceaa401e7831164adcb515e212"
    end
  end

  def install
    # The download is a single bare binary named for the URL basename
    # (voluntold-<os>-<arch>). Plain HTTP downloads don't carry the executable
    # bit, so set it before installing as `voluntold` — otherwise generating
    # the completions (which execs the binary) fails with EACCES. Then emit the
    # bash/zsh/fish completions from the binary itself.
    binary = Dir["voluntold-*"].first
    chmod "+x", binary
    bin.install binary => "voluntold"
    generate_completions_from_executable(bin/"voluntold", "completion")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/voluntold --version")
  end
end
