# typed: false
# frozen_string_literal: true

# voluntold — the agent runtime CLI.
#
# AUTO-GENERATED by the voluntold release CI (cli_release →
# cli/scripts/render-formula.sh) and force-pushed on every release. Do not edit
# by hand; changes will be overwritten. The binaries are obfuscated with garble
# and published to https://dl.voluntold.ai.
class Voluntold < Formula
  desc "Agent runtime that routes issue-board work to AI coding agents"
  homepage "https://voluntold.ai"
  version "0.11.31"

  on_macos do
    on_arm do
      url "https://dl.voluntold.ai/v0.11.31/voluntold-darwin-arm64"
      sha256 "a0e1b215705c3486ae2d4a15d5295ede15d17f0aa4aa273f407c017658691e0d"
    end
    on_intel do
      url "https://dl.voluntold.ai/v0.11.31/voluntold-darwin-amd64"
      sha256 "956724894e2629e54eb77b15b59be2e99b40c97d137e6fb0becfc53dc91f2669"
    end
  end

  on_linux do
    on_arm do
      url "https://dl.voluntold.ai/v0.11.31/voluntold-linux-arm64"
      sha256 "d43e9cf90c1e2330b35b1b263a8f3b174b84d1c04b6e7efda6c40d6585d1468a"
    end
    on_intel do
      url "https://dl.voluntold.ai/v0.11.31/voluntold-linux-amd64"
      sha256 "7b9e125fb6d8dc873d5a0868e076ab2ece0b114533094c6a8d8a042a5f121e25"
    end
  end

  def install
    # The download is a single bare binary named for the URL basename
    # (voluntold-<os>-<arch>). Plain HTTP downloads don't carry the executable
    # bit, so set it before installing as `voluntold` — otherwise generating
    # the completions (which execs the binary) fails with EACCES. Then emit the
    # bash/zsh/fish completions from the binary itself.
    binary = Dir["voluntold-*"].first
    chmod "+x", binary
    bin.install binary => "voluntold"
    generate_completions_from_executable(bin/"voluntold", "completion")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/voluntold --version")
  end
end
