# typed: false
# frozen_string_literal: true

# voluntold — the agent runtime CLI.
#
# AUTO-GENERATED by the voluntold release CI (cli_release →
# cli/scripts/render-formula.sh) and force-pushed on every release. Do not edit
# by hand; changes will be overwritten. The binaries are obfuscated with garble
# and published to https://dl.voluntold.ai.
class Voluntold < Formula
  desc "Agent runtime that routes issue-board work to AI coding agents"
  homepage "https://voluntold.ai"
  version "0.11.22"

  on_macos do
    on_arm do
      url "https://dl.voluntold.ai/v0.11.22/voluntold-darwin-arm64"
      sha256 "bc91e8b6adc3ae973f23eac5d24068b932cac35ae7295f82d4c0e44ce6726916"
    end
    on_intel do
      url "https://dl.voluntold.ai/v0.11.22/voluntold-darwin-amd64"
      sha256 "5ff11211674f4053bbbef9b8b7a986cf6de634bee955867639405cbab84eaf77"
    end
  end

  on_linux do
    on_arm do
      url "https://dl.voluntold.ai/v0.11.22/voluntold-linux-arm64"
      sha256 "447eb5cbeaaa488456718bf25eee0d87b30d0169165d6d35e3eb503dba52b0c4"
    end
    on_intel do
      url "https://dl.voluntold.ai/v0.11.22/voluntold-linux-amd64"
      sha256 "328f85062f13b29fafbe1593b59c6fb8e04b86d2d662a2efaef68fd494ec4204"
    end
  end

  def install
    # The download is a single bare binary named for the URL basename
    # (voluntold-<os>-<arch>). Plain HTTP downloads don't carry the executable
    # bit, so set it before installing as `voluntold` — otherwise generating
    # the completions (which execs the binary) fails with EACCES. Then emit the
    # bash/zsh/fish completions from the binary itself.
    binary = Dir["voluntold-*"].first
    chmod "+x", binary
    bin.install binary => "voluntold"
    generate_completions_from_executable(bin/"voluntold", "completion")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/voluntold --version")
  end
end
